### ISSUE TITLE
Add Navigation Popups to Horizen Academy

### ISSUE THREAD

**Issue by jtoownus** [HorizenOfficial/HorizenAcademy#272]
[Navigation Popups](https://en.wikipedia.org/wiki/Wikipedia:Tools/Navigation_popups) are a tool most notably used by Wikipedia to show users a preview of hyperlinks with an article. When the user hovers over a hyperlink, a preview pops up (see screenshots below).

Horizen Academy is using Bootstrap, which supports [a very similar feature](https://getbootstrap.com/docs/4.5/components/popovers/#four-directions). You would simply need to set a style according to a design provided by Horizen at request.

#### Expected behavior

- When a user hovers over a hyperlink that references another Horizen Academy article a preview pops up
- The preview shows a textbox and image
- Each article (.md file) needs to support two additional data fields in its preamble:
  * popup_preview_text: "*preview text*"
  * popup_preview_image: "file location" [optional]
- The navigation popup is clickable and takes the user to the linked article in a **new tab**
 
#### Not in scope for outside contributors

- The design for the popup will be provided by Horizen at request
- The preview texts and images will be provided by Horizen and are not part of the bounty

For questions please contact @jtoownus 

#### Example Screenshot

![Hovercard_english](https://user-images.githubusercontent.com/30371777/85540784-b1b2a780-b617-11ea-8e3b-0859109adfa5.png)

**Comment by jtoownus** [comment]
test

**Comment by morganblack25** [comment]
I do not understand this task well excuse me can you guide me please

**Comment by luisantoniocrag** [comment]
I'd like to solve this, Can I start to working on?

**Comment by luisantoniocrag** [comment]
I'd like to solve this.

**Comment by megaluck** [comment]
Hi @luisantoniocrag  , feel free to start ! Keep us updated on your progress.

**Comment by jtoownus** [comment]
@luisantoniocrag as soon as there is any progress to show, let me know. I'll mark the issue as Work in Progress so other contributors know it is being worked on.
Thanks for your contribution already!

**Comment by jtoownus** [comment]
@luisantoniocrag I'll get a design guide for you ASAP.

**Comment by jtoownus** [comment]
@luisantoniocrag Below are two designs, one for a navigation popup with image, the other one without an image. It would be great if your implementation made the image optional. Text, however, must be mandatory.

![image](https://user-images.githubusercontent.com/30371777/86369490-d0034d80-bc7e-11ea-9288-ff4ff4d78fbc.png)

![image](https://user-images.githubusercontent.com/30371777/86369593-f45f2a00-bc7e-11ea-90ef-139b1625606f.png)

**Comment by luisantoniocrag** [comment]
Thanks @jtoownus   @megaluck 

on it!

**Comment by simeon4real** [comment]
Hello, Is this issue still available for fixing?

**Comment by angievi** [comment]
Hi @simeon4real , a member of the community is already working on it, it has the WIP (work in progress) label.

Please feel free to check other HDE issues as we will be adding more of them soon. :)

**Comment by simeon4real** [comment]
Alright @angievi  I'll be keeping an eye out for more issues :) web dev related.

**Comment by riskywe** [comment]
Nice

**Comment by megaluck** [comment]
Any update @luisantoniocrag ?

**Comment by simeon4real** [comment]
Can I work on this?

**Comment by jtoownus** [comment]
@simeon4real It looks like there has already been some work done.
@luisantoniocrag You have an update for us?

**Comment by luisantoniocrag** [comment]
For personal reasons, it will take me a while to complete it @simeon4real is still interested I think he can complete it, sorry.

**Comment by rosariopabst** [comment]
> Can I work on this?

@simeon4real marking this WIP. What is an estimate completion?

**Comment by angievi** [comment]
> Can I work on this?

Hey @simeon4real how is it going with this task? Any ETC? let me know if you have questions or comments, thank you!

**Comment by Aubynj** [comment]
I'm here if it still a pending task so i can take it on

**Comment by angievi** [comment]
hi @simeon4real , any updates on this task? Please let us know if you planning on completing this and your ETC.
Otherwise we would like to pass this task to another community member who would like to contribute, thanks! :) Angie.

**Comment by fabiojsousa** [comment]
@jtoownus It seems this task is still available. Can we make a React component for this?

**Comment by angievi** [comment]
Hey @fabiojsousa, I'm gonna close the issue, thank you for offering a contribution.

Please take a look at some of the other HDE issues we currently have, you can still create a sidechain or test sidechain functionalities in our Sphere by Horizen wallet in case you are interested :) 

best,

Angie.

**Comment by fabiojsousa** [comment]
Hi!

I got an answer on discord that I could build this tooltip using React, so I made a component for this task, here is the link showing how it works: https://drive.google.com/file/d/1tOzPJVemyFrx2GzffUh_dfHdsAHiSB_F/view
