### ISSUE TITLE
Develop a structure for the topic "Open Source Software"

### ISSUE THREAD

**Issue by jtoownus** [HorizenOfficial/HorizenAcademy#288]
### Task Description

With the addition of the [HDE - Horizen Developer Environment](https://hde.horizen.global/) to the Horizen ecosystem, we want to expand the [Horizen Academy](https://academy.horizen.global/) with a new topic: Open Source Software (OSS).

We ask you to develop a structure for this new topic, grouped into three levels of complexity: Beginner, Advanced, and Expert. The structure of each level should be optimized for the following users:

- *Beginner*: Non-technical users interested in OSS
- *Advanced*: Technical users and developers without OSS experience
- *Expert*: Technical users and developers with OSS experience

### Scope & Submission Requirements

The scope of this task is developing a structure for this new topic. It should include the following:

- Chapters that articles are grouped in. The chapters should be consistent across the three levels. E.g. the first chapter for each level could be "Why contribute to OSS?". The higher the level, the more articles can be included per chapter. (See our [Content Overview Page](https://academy.horizen.global/content-overview/) to see how the other topics are structured)
- A list of articles per chapter
- A two-sentence description of each article's content

We accept your contribution in different formats. One suggestion would be using a markdown document table (see example template below) but google sheet or any other lucid format is acceptable. A short description of each article should be provided below the structure overview.

### Template

|    | Beginner | Advanced | Expert |
|---|---|---|---|
| **Chapter 1: xxx** |   |   |   |
| **Chapter 2: How to Contribute to OSS?** | 2.1 What is GitHub?  | 2.1 Git Workflows  | 2.1 The Horizen GitFlow |
|  |  | 2.2 Tools in and around GitHub  | 2.2 Horizen Contribution Guide |
|  |  |  | 2.3 Horizen Developer Policy |
| **Chapter 3: xxx** |   |   |   |

#### Beginner Level

- 1.1 xxx: *short description of the concepts this article should cover*
- 2.1 What is GitHub: Explain that GitHub is a user interface for the git version-control system. Explain what a version-control system is and what it does
- 2.2 xxx: *short description of the concepts this article should cover*

#### Advanced Level

- 1.1 xxx: *short description of the concepts this article should cover*
- 2.1 Git Workflows: Explain that there are different branching models and what a branching model is.
- 2.2 xxx: *short description of the concepts this article should cover*

**Comment by saulover** [comment]
Hi, I would like to undertake this task, how can I apply?

**Comment by jtoownus** [comment]
Just like that @saulover. Please confirm if you are going to start working on this issue and I'll apply the WIP label.

**Comment by saulover** [comment]
Sure I would like to start. However from the description, I believe I will need the content in order to be able to structure them, am I correct?

**Comment by jtoownus** [comment]
The content does not exist yet. I want to do this top down: first a high level structure of the entire content. Next, a rough plan for each article (the 2 sentence description mentioned above) and lastly, writing the actual articles. With a clear structure in mind, it becomes a lot easier to focus on the individual articles later on, as it is apparent what needs to be convered, and what is covered in other articles.

**Comment by jtoownus** [comment]
Hence, part of this task is also thinking about what concepts should be covered and then placing all these concepts in the different articles.

**Comment by saulover** [comment]
Ok, fair enough, I'd like to give it a go. I will do some initial research then and then categorize them into groups as mentioned in the task. Any deadline expectancy?

**Comment by jtoownus** [comment]
No deadline:) And always happy to help @saulover, if you have a first draft reach out and I'll provide you some feedback.

**Comment by RgisBr** [comment]
@jtoownus  i've a draft, is there still time for me to send?

**Comment by saulover** [comment]
> @jtoownus i've a draft, is there still time for me to send?

I'm already working on this @RgisBr...

**Comment by RgisBr** [comment]
> > @jtoownus i've a draft, is there still time for me to send?
> 
> I'm already working on this @RgisBr...

Ok, all right, i already have an article written for my university, i will save it for a next opportunity. Tk's

**Comment by CryptoManion** [comment]
Hello Horizen community and team!
I am just doing a test 
Good luck in the participation to this task ;)

**Comment by angievi** [comment]
> Ok, fair enough, I'd like to give it a go. I will do some initial research then and then categorize them into groups as mentioned in the task. Any deadline expectancy?

Hi @saulover how is it going with this task? any ETC? Let me know if you have any comments or questions, thanks!

**Comment by saulover** [comment]
> > Ok, fair enough, I'd like to give it a go. I will do some initial research then and then categorize them into groups as mentioned in the task. Any deadline expectancy?
> 
> Hi @saulover how is it going with this task? any ETC? Let me know if you have any comments or questions, thanks!

Hey @angievi will have the first draft ready by Friday, sound good?

**Comment by angievi** [comment]
sounds perfect! thank you :)

**Comment by Iago-Pereira** [comment]
Hi, I going to work on this. Do I have permission?

**Comment by sport83** [comment]
Fgff

**Comment by angievi** [comment]
> Hi, I going to work on this. Do I have permission?

Hey @Iago-Pereira currently this issue is no longer needed, I'm gonna close it now. You can still check on other HDE issues we have on our website: https://hde.horizen.io/ 
thanks!
Angie.
